import React from 'react';
import {Plus,Copy,Archive,RotateCcw,ArrowUpRight,ChevronRight,Save,Send,Eye,ImagePlus,ArrowLeft,ArrowRight,Trash2,Files,Package,Search,History,Link,Globe,Check,PanelRightClose} from 'lucide-react';
import {api,useLoad,Loading,ErrorBox,Empty,Heading,Field,SearchBox,Modal,Pill,date,categories} from './core';
import {MediaPicker} from './media';
import PageImages from './page-images';
export function ContentList({kind,notify}){
 const state=useLoad('/admin/content'),[search,setSearch]=React.useState(''),[filter,setFilter]=React.useState('active'),[create,setCreate]=React.useState(null),[error,setError]=React.useState('');
 const products=kind==='products',seo=kind==='seo';
 const items=(state.data?.items||[]).filter(x=>x.type!=='global'&&(seo||(products?x.type==='product':x.type!=='product'))).filter(x=>(filter==='archive'?x.archived:!x.archived)&&(filter!=='draft'||x.hasDraft)&&((x.title+' '+x.route).toLowerCase().includes(search.toLowerCase())));
 async function archive(item){setError('');if(!confirm(item.archived?'Восстановить страницу?':'Убрать страницу с сайта и переместить в архив?'))return;try{await api('/admin/content/'+item.id+'/archive',{method:'POST',body:{version:item.version,archived:!item.archived}});state.reload();notify(item.archived?'Страница восстановлена':'Страница перемещена в архив')}catch(e){setError(e.message)}}
 return <><Heading title={seo?'Поисковая оптимизация':products?'Товары':'Страницы'} description={seo?'Заголовки, описания и индексация каждой страницы.':products?'Каталог, характеристики и изображения техники.':'Управляйте содержимым и публикацией страниц.'}>{!seo&&<button className="button" onClick={()=>setCreate({})}><Plus size={18}/> {products?'Добавить товар':'Создать страницу'}</button>}</Heading><div className="toolbar"><SearchBox value={search} onChange={setSearch} placeholder={products?'Найти товар':'Найти страницу'}/><select aria-label="Статус" value={filter} onChange={e=>setFilter(e.target.value)}><option value="active">Все активные</option><option value="draft">С изменениями</option><option value="archive">Архив</option></select><span className="muted">{items.length} записей</span></div><ErrorBox>{error||state.error}</ErrorBox>{state.loading?<Loading/>:items.length?<div className="card table-wrap"><table><thead><tr><th>{products?'Товар':'Страница'}</th>{seo?<><th>SEO-заголовок</th><th>Описание</th><th>Индексация страницы</th></>:<><th>Статус</th><th>Изменено</th><th aria-label="Действия"/></>}</tr></thead><tbody>{items.map(p=><tr key={p.id}><td><a className="table-title" href={'#edit/'+p.id+(seo?'/seo':'')}>{products&&<img src={p.hero||'/_preserved/brand/ursar-transparent.svg'} alt=""/>}<span><b>{p.title}</b><small>{p.route}</small></span></a></td>{seo?<><td><a href={'#edit/'+p.id+'/seo'}>{p.seo.title||'Не задан'}</a></td><td><span className={'excerpt '+(!p.seo.description?'warning-text':'')}>{p.seo.description||'Добавьте описание'}</span></td><td><span className={'pill '+(p.seo.noindex?'amber':'')}>{p.seo.noindex?'Запрещена':'Разрешена'}</span></td></>:<><td><Pill item={p}/></td><td className="nowrap muted">{date(p.updatedAt)}</td><td><div className="actions tight"><a className="icon-button" href={'#edit/'+p.id} title="Редактировать"><ChevronRight size={19}/></a><button className="icon-button" title="Дублировать" onClick={()=>setCreate(p)}><Copy size={17}/></button>{!['home','globals'].includes(p.id)&&<button className="icon-button" title={p.archived?'Восстановить':'В архив'} onClick={()=>archive(p)}>{p.archived?<RotateCcw size={17}/>:<Archive size={17}/>}</button>}</div></td></>}</tr>)}</tbody></table></div>:<Empty title="Здесь пока пусто" text="Измените фильтр или создайте новую запись."/>}{seo&&<p className="hint">Общий запрет индексации в настройках сайта имеет приоритет над настройкой отдельной страницы.</p>}{create&&<CreateContent products={products} duplicate={create.id?create:null} items={state.data?.items||[]} onClose={()=>setCreate(null)} notify={notify}/>}</>
}
function CreateContent({products,duplicate,items,onClose,notify}){
 const templates=items.filter(x=>!x.archived&&(products?x.type==='product':x.type==='page'));
 const [title,setTitle]=React.useState(duplicate?duplicate.title+' — копия':''),[slug,setSlug]=React.useState(duplicate?duplicate.route.split('/').filter(Boolean).pop()+'-copy':''),[template,setTemplate]=React.useState(duplicate?.id||templates[0]?.id||''),[busy,setBusy]=React.useState(false),[error,setError]=React.useState('');
 async function save(e){e.preventDefault();setBusy(true);setError('');try{const p=await api('/admin/content',{method:'POST',body:{title,slug,templateId:template,duplicate:!!duplicate}});notify('Черновик создан');onClose();location.hash='edit/'+p.id;}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <Modal title={duplicate?'Дублировать запись':products?'Новый товар':'Новая страница'} onClose={onClose}><form onSubmit={save}><Field label="Название" value={title} onChange={e=>setTitle(e.target.value)} required autoFocus maxLength={200}/><Field label="Адрес" hint={products?'/product/ваш-адрес/':'/ваш-адрес/'} value={slug} onChange={e=>setSlug(e.target.value.toLowerCase())} required pattern="[a-z0-9][a-z0-9-]*" placeholder="novaya-model" maxLength={150}/>{!duplicate&&<Field label="Взять оформление страницы"><select value={template} onChange={e=>setTemplate(e.target.value)}>{templates.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></Field>}<p className="hint">Запись появится на сайте после публикации. До этого можно изменить все тексты и изображения.</p><ErrorBox>{error}</ErrorBox><div className="actions end"><button className="button secondary" type="button" onClick={onClose}>Отмена</button><button className="button" disabled={busy||!template}>Создать черновик</button></div></form></Modal>
}
export function Editor({id,initialTab,notify}){
 const state=useLoad('/admin/content/'+id),[record,setRecord]=React.useState(null),[data,setData]=React.useState(null),[saved,setSaved]=React.useState(''),[tab,setTab]=React.useState(initialTab||'content'),[section,setSection]=React.useState(''),[search,setSearch]=React.useState(''),[busy,setBusy]=React.useState(false),[error,setError]=React.useState(''),[picker,setPicker]=React.useState(null),[preview,setPreview]=React.useState(false),[previewVersion,setPreviewVersion]=React.useState(0),[selected,setSelected]=React.useState('');const frame=React.useRef(null);
 React.useEffect(()=>{if(state.data){if(!initialTab&&state.data.type==='product')setTab('product');setRecord(state.data);setData(state.data.data);setSaved(JSON.stringify(state.data.data));setSection(state.data.fields.find(f=>f.kind==='text'&&/^h[12]$/.test(f.tag)&&f.section!=='Содержимое страницы')?.section||state.data.fields[0]?.section||'');setError('')}},[state.data]);
 React.useEffect(()=>setTab(initialTab||'content'),[id,initialTab]);
 const dirty=!!data&&JSON.stringify(data)!==saved;
 React.useEffect(()=>{window.ursarDirty=dirty;const block=e=>{if(dirty){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',block);return()=>{window.ursarDirty=false;window.removeEventListener('beforeunload',block)}},[dirty]);
 React.useEffect(()=>{const receive=e=>{if(e.origin!==location.origin||e.source!==frame.current?.contentWindow||e.data?.type!=='ursar-field')return;const f=record?.fields.find(f=>f.id===e.data.id);if(f){setTab('content');setSection(f.section);setSearch('');setSelected(f.id);setTimeout(()=>document.getElementById('field-'+f.id)?.focus(),50)}else if(e.data.id.startsWith('g_'))notify('Этот текст редактируется в разделе «Общие блоки».')};window.addEventListener('message',receive);return()=>window.removeEventListener('message',receive)},[record,notify]);
 React.useEffect(()=>{if(preview&&data)frame.current?.contentWindow?.postMessage({type:'ursar-preview-fields',fields:data.fields},location.origin)},[data,preview]);
 const update=(key,value)=>setData(d=>({...d,[key]:value}));
 const product=(key,value)=>setData(d=>({...d,product:{...d.product,[key]:value}}));
 const seo=(key,value)=>setData(d=>({...d,seo:{...d.seo,[key]:value}}));
 const changeField=(id,value)=>setData(d=>({...d,fields:{...d.fields,[id]:value}}));
 async function save(publish=false){setBusy(true);setError('');try{const r=await api('/admin/content/'+id+(publish?'/publish':''),{method:publish?'POST':'PUT',body:{version:record.version,data}});setRecord(old=>({...old,...r}));setData(r.data);setSaved(JSON.stringify(r.data));setPreviewVersion(x=>x+1);notify(publish?'Изменения опубликованы на сайте':'Черновик сохранён');}catch(e){setError(e.message)}finally{setBusy(false)}}
 if(state.loading&&!record)return <Loading/>;if(state.error)return <ErrorBox>{state.error}</ErrorBox>;if(!data||!record)return <Loading/>;
 const isProduct=record.type==='product',isGlobal=record.type==='global';
 const sections=[...new Set(record.fields.map(f=>f.section))];const shown=record.fields.filter(f=>search?((data.fields[f.id]??f.value)+' '+f.label).toLowerCase().includes(search.toLowerCase()):f.section===section);
 const tabs=[...(isProduct?[['product','Товар']]:[]),['content','Тексты'],['images','Изображения'],...(!isGlobal?[['seo','SEO']]:[]),['history','История']];
 return <><div className="editor-heading"><a className="back-link" href={'#'+(isGlobal?'overview':isProduct?'products':'pages')}><ArrowLeft size={16}/> {isGlobal?'Обзор':isProduct?'Товары':'Страницы'}</a><div className="page-heading"><div><h1>{data.title}</h1><div className="actions"><Pill item={{...record,hasDraft:record.hasDraft||dirty}}/><span className="muted">{dirty?'Есть несохранённые изменения':date(record.updatedAt)}</span>{!isGlobal&&record.isPublished&&<a href={record.route} target="_blank" rel="noreferrer" className="text-link">На сайте <ArrowUpRight size={14}/></a>}</div></div><div className="actions"><button className="button secondary" onClick={()=>setPreview(!preview)}><Eye size={17}/>{preview?'Скрыть':'Предпросмотр'}</button><button className="button secondary" disabled={busy} onClick={()=>save(false)}><Save size={17}/>Черновик</button><button className="button" disabled={busy} onClick={()=>save(true)}><Send size={17}/>Опубликовать</button></div></div></div><ErrorBox>{error}</ErrorBox><div className={'editor-layout '+(preview?'with-preview':'')}><section className="editor-panel"><div className="tabs" role="tablist">{tabs.map(([key,label])=><button key={key} role="tab" aria-selected={tab===key} className={tab===key?'active':''} onClick={()=>setTab(key)}>{label}</button>)}</div>
 {tab==='product'&&isProduct&&<div className="editor-card"><h2>Основное о товаре</h2><Field label="Название товара" value={data.product.name} onChange={e=>product('name',e.target.value)} maxLength={250}/><div className="form-grid"><Field label="Адрес товара" hint={'/product/'+data.product.slug+'/'} value={data.product.slug} onChange={e=>product('slug',e.target.value)} maxLength={150}/><Field label="Категория"><select value={data.product.category} onChange={e=>product('category',e.target.value)}>{Object.entries(categories).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></Field><Field label="Цена, ₽" type="number" min="0" max="1000000000" hint="Оставьте пустым, если цена по запросу." value={data.product.price} onChange={e=>product('price',e.target.value)}/><Field label="Наличие"><select value={data.product.availability} onChange={e=>product('availability',e.target.value)}><option value="request">По запросу</option><option value="in-stock">В наличии</option><option value="preorder">Под заказ</option><option value="out-of-stock">Нет в наличии</option></select></Field></div><Field label="Краткое описание"><textarea rows={7} value={data.product.description} onChange={e=>product('description',e.target.value)}/></Field><h3>Галерея товара</h3><Gallery values={data.product.gallery} onChange={v=>product('gallery',v)} onAdd={()=>setPicker('gallery')}/><p className="hint">Первое изображение используется в каталоге. Подробное описание и характеристики редактируются на вкладке «Тексты».</p></div>}
 {tab==='content'&&<><div className="editor-tools"><SearchBox value={search} onChange={setSearch} placeholder="Поиск по всем текстам"/><select aria-label="Раздел страницы" value={section} onChange={e=>{setSection(e.target.value);setSearch('')}}>{sections.map(s=><option key={s}>{s}</option>)}</select></div><div className="editor-card"><h2>{search?'Результаты поиска':section}</h2><p className="hint">{shown.length} полей · Изменяется только содержимое, оформление сохраняется.</p>{shown.map(f=><div className={'content-field '+(selected===f.id?'selected':'')} key={f.id}><Field label={f.label+(f.attribute==='href'?'':'')} hint={f.kind==='link'?'Ссылка, телефон (tel:) или email (mailto:).':undefined}>{f.kind==='link'?<input id={'field-'+f.id} value={data.fields[f.id]??f.value} onChange={e=>changeField(f.id,e.target.value)}/>:<textarea id={'field-'+f.id} rows={((data.fields[f.id]??f.value).length>180?5:2)} value={data.fields[f.id]??f.value} onChange={e=>changeField(f.id,e.target.value)}/>}</Field>{Object.hasOwn(data.fields,f.id)&&<button className="reset-field" onClick={()=>changeField(f.id,f.defaultValue??f.value)}><RotateCcw size={12}/> Исходный текст</button>}</div>)}{!shown.length&&<Empty title="Совпадений нет"/>}</div></>}
 {tab==='images'&&<div className="editor-card"><h2>{isProduct?'Галерея и изображения':'Изображения страницы'}</h2>{isProduct&&<Gallery values={data.product.gallery} onChange={v=>product('gallery',v)} onAdd={()=>setPicker('gallery')}/>}<p className="muted">В медиатеке можно заменить изображение во всех местах его использования, включая фоновые изображения.</p><a href="#media" className="button secondary"><ImagePlus size={17}/>Открыть медиатеку</a>{isGlobal&&Object.keys(data.mediaMap||{}).length>0&&<div className="notice">Настроено замен изображений: {Object.keys(data.mediaMap).length}. Они публикуются вместе с общими блоками.</div>}<PageImages ids={record.images} notify={notify} mediaMap={data.mediaMap} onReplace={map=>setData(d=>({...d,mediaMap:{...d.mediaMap,...map}}))}/></div>}
 {tab==='seo'&&<div className="editor-card"><h2>Поиск и социальные сети</h2>{!isProduct&&<><Field label="Название в админке" value={data.title} onChange={e=>update('title',e.target.value)}/><Field label="Адрес страницы" hint="Например: /about/ . При смене адреса старый будет перенаправлять на новый." value={data.route} onChange={e=>update('route',e.target.value)}/></>}<Field label="Заголовок в поиске (title)" hint={`${data.seo.title.length} символов · обычно 50–70`} value={data.seo.title} maxLength={200} onChange={e=>seo('title',e.target.value)}/><Field label="Описание в поиске (description)" hint={`${data.seo.description.length} символов · обычно 120–160`}><textarea rows={4} value={data.seo.description} maxLength={1000} onChange={e=>seo('description',e.target.value)}/></Field><div className="search-preview"><small>ursar.ru{data.route}</small><strong>{data.seo.title||data.title+' — URSAR'}</strong><p>{data.seo.description||'Добавьте описание страницы.'}</p></div><Field label="Канонический адрес" hint="Оставьте пустым, чтобы использовать адрес этой страницы." value={data.seo.canonical} onChange={e=>seo('canonical',e.target.value)}/><label className="checkbox"><input type="checkbox" checked={data.seo.noindex} onChange={e=>seo('noindex',e.target.checked)}/>Запретить индексацию этой страницы</label><hr/><h3>Карточка ссылки в мессенджерах</h3><Field label="Заголовок карточки" value={data.seo.ogTitle} onChange={e=>seo('ogTitle',e.target.value)}/><Field label="Описание карточки"><textarea rows={3} value={data.seo.ogDescription} onChange={e=>seo('ogDescription',e.target.value)}/></Field><div className="og-image">{data.seo.ogImage&&<img src={data.seo.ogImage} alt="Обложка ссылки"/>}<button className="button secondary" onClick={()=>setPicker('og')}>Выбрать обложку</button>{data.seo.ogImage&&<button className="icon-button" title="Удалить обложку" onClick={()=>seo('ogImage','')}><Trash2 size={17}/></button>}</div></div>}
 {tab==='history'&&<HistoryPanel id={id} record={record} dirty={dirty} onRestore={r=>{setRecord(x=>({...x,...r}));setData(r.data);setSaved(JSON.stringify(r.data));setPreviewVersion(x=>x+1);notify('Версия восстановлена в черновик')}}/>}
 </section>{preview&&<aside className="preview-panel"><div><span>Предпросмотр черновика</span><button className="icon-button" title="Закрыть предпросмотр" onClick={()=>setPreview(false)}><PanelRightClose size={18}/></button></div><p>Нажмите на текст, чтобы найти его в редакторе. Для проверки изображений и SEO сначала сохраните черновик.</p><iframe ref={frame} title="Предпросмотр страницы" key={previewVersion} src={'/?cms_preview='+id} onLoad={()=>frame.current?.contentWindow?.postMessage({type:'ursar-preview-fields',fields:data.fields},location.origin)}/></aside>}</div>{picker&&<MediaPicker notify={notify} onClose={()=>setPicker(null)} onPick={m=>{if(picker==='gallery')product('gallery',[...data.product.gallery,m.url]);else seo('ogImage',m.url);setPicker(null)}}/>}</>
}
function Gallery({values,onChange,onAdd}){function move(index,delta){const next=[...values];[next[index],next[index+delta]]=[next[index+delta],next[index]];onChange(next)}return <div className="gallery-grid">{values.map((url,i)=><div key={url+'-'+i} className="gallery-item"><img src={url} alt={'Фото '+(i+1)}/><div><span>{i===0?'Главное':i+1}</span><button className="icon-button" title="Левее" disabled={i===0} onClick={()=>move(i,-1)}><ArrowLeft size={15}/></button><button className="icon-button" title="Правее" disabled={i===values.length-1} onClick={()=>move(i,1)}><ArrowRight size={15}/></button><button className="icon-button" title="Убрать из галереи" onClick={()=>onChange(values.filter((_,j)=>j!==i))}><Trash2 size={15}/></button></div></div>)}<button className="gallery-add" onClick={onAdd}><ImagePlus size={26}/>Добавить фото</button></div>}
function HistoryPanel({id,record,dirty,onRestore}){const state=useLoad('/admin/content/'+id+'/revisions',[record.version]),[busy,setBusy]=React.useState(false),[error,setError]=React.useState('');async function restore(revisionId){if(!confirm(dirty?'Несохранённые изменения будут заменены. Восстановить версию в черновик?':'Восстановить эту версию в черновик?'))return;setBusy(true);setError('');try{onRestore(await api('/admin/content/'+id+'/restore',{method:'POST',body:{revisionId,version:record.version}}));state.reload()}catch(e){setError(e.message)}finally{setBusy(false)}}return <div className="editor-card"><h2>История изменений</h2><p className="muted">Восстановление создаёт черновик. Опубликованная версия изменится только после нажатия «Опубликовать».</p><ErrorBox>{error||state.error}</ErrorBox>{state.loading?<Loading/>:state.data?.items.length?state.data.items.map(r=><div className="history-row" key={r.id}><History size={18}/><div><b>{{initial:'Исходная версия',save:'Сохранён черновик',publish:'Опубликовано'}[r.action]||r.action}</b><small>{date(r.created_at)} · {r.actor}</small></div><button className="button secondary small" disabled={busy} onClick={()=>restore(r.id)}>Восстановить</button></div>):<Empty title="История пока пуста" text="Здесь будут сохраняться версии после первого изменения."/>}</div>}
