import React from 'react';
import {createRoot} from 'react-dom/client';
import {LayoutDashboard,Files,Package,Images,Search,Inbox,Settings as SettingsIcon,ArrowUpRight,ChevronRight,Menu,Globe,ShieldCheck,LogOut,LockKeyhole,Eye,EyeOff,X} from 'lucide-react';
import {api,setCsrf,useLoad,Loading,ErrorBox,Empty,Heading,Pill,Toast,date,roles} from './core';
import {ContentList,Editor} from './content';
import {MediaPage} from './media';
import {Leads,Settings} from './management';
import './style.css';
const nav=[['overview','Обзор',LayoutDashboard,'all'],['pages','Страницы',Files,'content'],['products','Товары',Package,'content'],['media','Медиатека',Images,'content'],['seo','SEO',Search,'content'],['leads','Обращения',Inbox,'leads'],['globals','Общие блоки',Globe,'content'],['settings','Настройки',SettingsIcon,'all']];
const allowed=(role,type)=>type==='all'||role==='admin'||type==='content'&&role==='editor'||type==='leads'&&role==='manager';
function App(){
 const [user,setUser]=React.useState(null),[loading,setLoading]=React.useState(true),[authError,setAuthError]=React.useState(''),[route,setRoute]=React.useState(location.hash.slice(1)||'overview'),[mobile,setMobile]=React.useState(false),[toast,setToast]=React.useState(null);
 const notify=React.useCallback((text,error=false)=>setToast({text,error}),[]);
 React.useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(null),4500);return()=>clearTimeout(t)}},[toast]);
 React.useEffect(()=>{api('/auth/session').then(r=>{setUser(r.user);setCsrf(r.csrf)}).catch(e=>setAuthError(e.message)).finally(()=>setLoading(false));const expire=()=>{setUser(null);setCsrf('');setAuthError('Сессия завершена. Войдите снова.');window.ursarDirty=false};const hash=()=>{setRoute(location.hash.slice(1)||'overview');setMobile(false);window.scrollTo(0,0)};window.addEventListener('ursar-unauthorized',expire);window.addEventListener('hashchange',hash);return()=>{window.removeEventListener('ursar-unauthorized',expire);window.removeEventListener('hashchange',hash)}},[]);
 function guard(e){const link=e.target.closest('a[href]');if(link&&window.ursarDirty&&!link.target&&(link.getAttribute('href').startsWith('#')||link.pathname==='/admin/')){if(!confirm('Есть несохранённые изменения. Покинуть редактор?')){e.preventDefault();e.stopPropagation()}else window.ursarDirty=false;}}
 async function logout(){if(window.ursarDirty&&!confirm('Выйти без сохранения изменений?'))return;try{await api('/auth/logout',{method:'POST'});setUser(null);setCsrf('');window.ursarDirty=false;}catch(e){notify(e.message,true)}}
 if(loading)return <div className="login-page"><Loading/></div>;
 if(!user)return <Login error={authError} onLogin={r=>{setUser(r.user);setCsrf(r.csrf);setAuthError('')}}/>;
 const parts=route.split('/'),key=parts[0];const active=key==='edit'?'pages':key;
 const item=nav.find(x=>x[0]===active)||nav[0];const permitted=allowed(user.role,item[3]);
 return <div className="workspace" onClickCapture={guard}>{mobile&&<button className="sidebar-overlay" aria-label="Закрыть меню" onClick={()=>setMobile(false)}/>}<aside className={'sidebar '+(mobile?'open':'')}><a className="brand" href="#overview"><img src="/_preserved/brand/ursar-transparent.svg" alt="URSAR"/><span>URSAR<small>УПРАВЛЕНИЕ САЙТОМ</small></span></a><div className="nav-caption">РАБОЧЕЕ ПРОСТРАНСТВО</div><nav>{nav.filter(n=>allowed(user.role,n[3])).map(([key,label,Icon])=><a key={key} className={key===active?'active':''} href={'#'+key}><Icon size={19}/>{label}</a>)}</nav><div className="sidebar-bottom"><a href="/" target="_blank" rel="noreferrer"><ArrowUpRight size={18}/>Открыть сайт</a><div className="profile"><div className="avatar">{user.name.slice(0,1)}</div><span>{user.name}<small>{roles[user.role]}</small></span><button className="icon-button logout" title="Выйти" onClick={logout}><LogOut size={18}/></button></div></div></aside><main><header className="topbar"><span><button className="icon-button mobile-menu" aria-label="Открыть меню" onClick={()=>setMobile(true)}><Menu size={22}/></button>Сайт URSAR <ChevronRight size={15}/> {key==='edit'?'Редактор':item[1]}</span><a className="button secondary small" href="/" target="_blank" rel="noreferrer">Посмотреть сайт <ArrowUpRight size={16}/></a></header><div className={'content '+(key==='edit'||key==='globals'?'editing':'')}>{!permitted?<Empty title="Нет доступа к разделу" text="Обратитесь к администратору сайта."/>:key==='overview'?<Dashboard user={user}/>:['pages','products','seo'].includes(key)?<ContentList key={key} kind={key} notify={notify}/>:key==='edit'?<Editor key={parts[1]} id={parts[1]} initialTab={parts[2]} notify={notify}/>:key==='globals'?<Editor key="globals" id="globals" notify={notify}/>:key==='media'?<MediaPage notify={notify}/>:key==='leads'?<Leads notify={notify}/>:key==='settings'?<Settings user={user} notify={notify}/>:<Empty title="Раздел не найден"/>}</div></main><Toast value={toast}/></div>
}
function Login({onLogin,error:initialError}){const [email,setEmail]=React.useState(''),[password,setPassword]=React.useState(''),[show,setShow]=React.useState(false),[busy,setBusy]=React.useState(false),[error,setError]=React.useState(initialError);async function submit(e){e.preventDefault();setBusy(true);setError('');try{onLogin(await api('/auth/login',{method:'POST',body:{email,password}}));setPassword('')}catch(e){setError(e.message)}finally{setBusy(false)}}return <div className="login-page"><div className="login-brand-panel"><img src="/_preserved/brand/ursar-transparent.svg" alt="URSAR"/><span>URSAR</span><h1>Ваш сайт.<br/>Под вашим управлением.</h1><p>Контент, техника и обращения клиентов<br/>в одном рабочем пространстве.</p><small>ПАНЕЛЬ УПРАВЛЕНИЯ URSAR</small></div><div className="login-form-panel"><form onSubmit={submit}><div className="login-icon"><LockKeyhole size={27}/></div><h2>Добро пожаловать</h2><p>Войдите, чтобы управлять сайтом.</p><label className="field"><span>Email</span><input type="email" value={email} onChange={e=>setEmail(e.target.value)} required autoComplete="username" autoFocus placeholder="admin@ursar.ru"/></label><label className="field"><span>Пароль</span><div className="password-input"><input type={show?'text':'password'} value={password} onChange={e=>setPassword(e.target.value)} required autoComplete="current-password"/><button type="button" className="icon-button" aria-label={show?'Скрыть пароль':'Показать пароль'} onClick={()=>setShow(!show)}>{show?<EyeOff size={19}/>:<Eye size={19}/>}</button></div></label><ErrorBox>{error}</ErrorBox><button className="button login-submit" disabled={busy}>{busy?'Входим…':'Войти в админку'}<ChevronRight size={18}/></button><p className="login-help">Если забыли пароль, обратитесь к администратору сайта.</p><a href="/" className="text-link">Открыть сайт <ArrowUpRight size={15}/></a></form></div></div>}
function Dashboard({user}){
 const state=useLoad('/admin/dashboard');const data=state.data,canContent=allowed(user.role,'content'),canLeads=allowed(user.role,'leads');
 return <><Heading title="Всё под контролем." description="Контент, товары и обращения — в одном месте."><span className="date">{new Intl.DateTimeFormat('ru',{day:'numeric',month:'long',year:'numeric'}).format(new Date())}</span></Heading><ErrorBox>{state.error}</ErrorBox>{state.loading?<Loading/>:<><div className="stats">{[['Страницы сайта',data?.counts.pages,Files,'pages'],['Товары в каталоге',data?.counts.products,Package,'products'],['Изображения',data?.counts.media,Images,'media'],['Новые обращения',data?.counts.newLeads,Inbox,'leads']].filter(x=>x[3]==='leads'?canLeads:canContent).map(([label,value,Icon,key])=><a className="stat" href={'#'+key} key={label}><div><span>{label}</span><Icon size={20}/></div><strong>{value??'—'}</strong><small>{key==='leads'?'Ждут вашего ответа':'Доступно для управления'}</small></a>)}</div><div className="dashboard-grid">{canContent&&<section className="card"><div className="card-heading"><h2>Страницы сайта</h2><a href="#pages">Все страницы <ChevronRight size={16}/></a></div>{data?.pages.slice(0,5).map(p=><a className="page-row" key={p.id} href={'#edit/'+p.id}><div className="page-icon"><Files size={20}/></div><div><b>{p.title}</b><small>{p.route}</small></div><Pill item={p}/><ChevronRight size={18}/></a>)}</section>}{canLeads&&<section className="card"><div className="card-heading"><h2>Последние обращения</h2><a href="#leads"><Inbox size={20}/></a></div>{data?.leads.length?data.leads.map(l=><a href="#leads" key={l.id} className="page-row"><div className="page-icon"><Inbox size={18}/></div><div><b>{l.name}</b><small>{l.message||l.phone||l.email}</small></div><span className="muted">{date(l.created_at)}</span></a>):<Empty title="Пока нет обращений" text="Здесь появятся сообщения, которые посетители отправят через формы сайта."/>}</section>}</div>{canContent&&<section className="card product-preview"><div className="card-heading"><h2>Каталог URSAR</h2><a href="#products">Управление товарами <ChevronRight size={16}/></a></div><div className="product-mini-grid">{data?.products.slice(0,4).map(p=><a key={p.id} href={'#edit/'+p.id+'/product'}><img src={p.hero||'/_preserved/brand/ursar-transparent.svg'} alt=""/><div><small>{p.product.category==='lawn-mower'?'ГАЗОНОКОСИЛКИ':'МИНИ-ПОГРУЗЧИКИ'}</small><b>{p.product.name}</b></div><ChevronRight size={18}/></a>)}</div></section>}<div className="bottom-note"><ShieldCheck size={16}/> Изменения сохраняются в черновик до публикации.</div></>}</>
}
createRoot(document.getElementById('root')).render(<App/>);
