import React from 'react';
import {Download,Inbox,Mail,Phone,ExternalLink,Save,Archive,RotateCcw,Plus,Users,ShieldCheck,KeyRound,History,Settings as SettingsIcon} from 'lucide-react';
import {api,setCsrf,useLoad,Loading,ErrorBox,Empty,Heading,Field,SearchBox,Modal,date,roles,Pagination} from './core';
const statuses={new:'Новое',working:'В работе',closed:'Закрыто',spam:'Спам'};
export function Leads({notify}){
 const [search,setSearch]=React.useState(''),[query,setQuery]=React.useState(''),[status,setStatus]=React.useState(''),[page,setPage]=React.useState(1),[selected,setSelected]=React.useState(null);
 React.useEffect(()=>{const t=setTimeout(()=>{setQuery(search);setPage(1)},250);return()=>clearTimeout(t)},[search]);
 const state=useLoad('/admin/leads?q='+encodeURIComponent(query)+'&status='+status+'&page='+page);
 return <><Heading title="Обращения" description="Сообщения с форм сайта и история работы с ними."><a className="button secondary" href="/api/admin/leads/export"><Download size={17}/>Выгрузить CSV</a></Heading><div className="lead-counts">{Object.entries(statuses).map(([key,label])=><button key={key} className={status===key?'active':''} onClick={()=>{setStatus(status===key?'':key);setPage(1)}}><span>{label}</span><b>{state.data?.counts.find(c=>c.status===key)?.count||0}</b></button>)}</div><div className="toolbar"><SearchBox value={search} onChange={setSearch} placeholder="Имя, телефон, email или текст"/><select aria-label="Фильтр обращений" value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="">Все обращения</option>{Object.entries(statuses).map(([id,name])=><option key={id} value={id}>{name}</option>)}<option value="trash">Архив</option></select><button className="button secondary small" onClick={state.reload}>Обновить</button></div><ErrorBox>{state.error}</ErrorBox>{state.loading?<Loading/>:state.data?.items.length?<div className="card table-wrap"><table><thead><tr><th>Посетитель</th><th>Сообщение</th><th>Статус</th><th>Получено</th></tr></thead><tbody>{state.data.items.map(l=><tr key={l.id} className="clickable" onClick={()=>setSelected(l)}><td><button className="text-button" onClick={e=>{e.stopPropagation();setSelected(l)}}><b>{l.name}</b></button><small className="block muted">{l.phone||l.email}</small></td><td><span className="excerpt">{l.message||'Без сообщения'}</span><small className="block muted">{l.form_name}</small></td><td><span className={'pill '+(l.status==='new'?'amber':l.status==='spam'?'gray':'')}>{statuses[l.status]}</span></td><td className="nowrap muted">{date(l.created_at)}</td></tr>)}</tbody></table></div>:<Empty title={query?'Ничего не найдено':'Обращений пока нет'} text="Когда посетитель отправит форму, сообщение появится здесь." icon={Inbox}/>}<Pagination page={page} total={state.data?.total||0} size={50} onChange={setPage}/>{selected&&<LeadDetail lead={selected} onClose={()=>setSelected(null)} onSaved={()=>state.reload()} notify={notify}/>}</>
}
function LeadDetail({lead,onClose,onSaved,notify}){const [status,setStatus]=React.useState(lead.status),[notes,setNotes]=React.useState(lead.notes),[error,setError]=React.useState(''),[busy,setBusy]=React.useState(false);async function save(archived=lead.archived){setBusy(true);setError('');try{await api('/admin/leads/'+lead.id,{method:'PUT',body:{status,notes,archived}});notify(archived?'Обращение в архиве':'Обращение обновлено');onSaved();onClose()}catch(e){setError(e.message)}finally{setBusy(false)}}return <Modal title={'Обращение от '+lead.name} onClose={onClose} wide><div className="lead-detail"><div><p className="muted">{date(lead.created_at)} · {lead.form_name}</p><div className="contact-links">{lead.phone&&<a href={'tel:'+lead.phone.replace(/[^+\d]/g,'')}><Phone size={18}/>{lead.phone}</a>}{lead.email&&<a href={'mailto:'+lead.email}><Mail size={18}/>{lead.email}</a>}</div><div className="message-text">{lead.message||'Посетитель оставил контактные данные без сообщения.'}</div>{lead.page.startsWith('/')&&!lead.page.startsWith('//')&&<a href={lead.page} target="_blank" rel="noreferrer" className="text-link">Страница отправки <ExternalLink size={15}/></a>}</div><div><Field label="Статус"><select value={status} onChange={e=>setStatus(e.target.value)}>{Object.entries(statuses).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></Field><Field label="Внутренняя заметка" hint="Видна только сотрудникам в админке."><textarea rows={8} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Результат звонка, договорённости, следующий шаг…"/></Field><ErrorBox>{error}</ErrorBox><div className="actions"><button className="button" disabled={busy} onClick={()=>save()}><Save size={16}/>Сохранить</button><button className="button secondary" disabled={busy} onClick={()=>save(!lead.archived)}>{lead.archived?<RotateCcw size={16}/>:<Archive size={16}/>} {lead.archived?'Вернуть':'В архив'}</button></div></div></div></Modal>}
export function Settings({user,notify}){
 const [tab,setTab]=React.useState(user.role==='admin'?'site':'password');
 const tabs=user.role==='admin'?[['site','Сайт и формы'],['users','Пользователи'],['password','Мой пароль'],['audit','Журнал действий']]:[['password','Мой пароль']];
 return <><Heading title="Настройки" description="Параметры сайта, доступ сотрудников и безопасность."/><div className="tabs standalone">{tabs.map(([key,name])=><button key={key} className={key===tab?'active':''} onClick={()=>setTab(key)}>{name}</button>)}</div>{tab==='site'&&<SiteSettings notify={notify}/>} {tab==='users'&&<UserSettings notify={notify} current={user}/>} {tab==='password'&&<PasswordSettings notify={notify}/>} {tab==='audit'&&<Audit/>}</>
}
function SiteSettings({notify}){
 const state=useLoad('/admin/settings'),[data,setData]=React.useState(null),[version,setVersion]=React.useState(0),[busy,setBusy]=React.useState(false),[error,setError]=React.useState('');
 React.useEffect(()=>{if(state.data){setData(state.data.data);setVersion(state.data.version)}},[state.data]);const change=(key,value)=>setData(d=>({...d,[key]:value}));
 async function save(e){e.preventDefault();setBusy(true);setError('');try{const r=await api('/admin/settings',{method:'PUT',body:{data,version}});setData(r.data);setVersion(r.version);notify('Настройки применены')}catch(e){setError(e.message)}finally{setBusy(false)}}
 if(state.loading||!data)return <><ErrorBox>{state.error}</ErrorBox><Loading/></>;
 return <form onSubmit={save} className="settings-grid"><div className="card padded"><h2>Основные параметры</h2><Field label="Название сайта" value={data.siteName} onChange={e=>change('siteName',e.target.value)} required/><Field label="Описание по умолчанию"><textarea rows={4} value={data.description} onChange={e=>change('description',e.target.value)}/></Field><label className="checkbox prominent"><input type="checkbox" checked={data.noindex} onChange={e=>change('noindex',e.target.checked)}/><span>Запретить индексацию всего сайта<small>Включает запрет в robots.txt и метатегах. Для демонстрационного сайта оставьте включённым.</small></span></label><hr/><h2>Формы обратной связи</h2><Field label="Сообщение после отправки"><textarea rows={3} required value={data.formSuccess} onChange={e=>change('formSuccess',e.target.value)}/></Field><Field label="Текст согласия на обработку данных"><textarea rows={3} required value={data.consentText} onChange={e=>change('consentText',e.target.value)}/></Field><ErrorBox>{error}</ErrorBox><button className="button" disabled={busy}><Save size={17}/>Сохранить настройки</button></div><div><div className="card padded"><ShieldCheck size={27}/><h2>Доступ к сайту</h2><p className="muted">{state.data.origin}</p><p>Обращения хранятся в закрытой базе и доступны администраторам и менеджерам.</p><p className="hint">Почтовые уведомления не настроены. Проверяйте новые сообщения в разделе «Обращения».</p></div><div className="card padded mt"><Download size={25}/><h2>Экспорт содержимого</h2><p className="muted">Страницы, товары, SEO и настройки. Пароли и обращения в этот файл не включаются.</p><a className="button secondary" href="/api/admin/export">Скачать JSON</a></div></div></form>
}
function PasswordSettings({notify}){const [current,setCurrent]=React.useState(''),[password,setPassword]=React.useState(''),[repeat,setRepeat]=React.useState(''),[busy,setBusy]=React.useState(false),[error,setError]=React.useState('');async function save(e){e.preventDefault();if(password!==repeat){setError('Новые пароли не совпадают.');return;}setBusy(true);setError('');try{const r=await api('/auth/password',{method:'PUT',body:{current,password}});setCsrf(r.csrf);setCurrent('');setPassword('');setRepeat('');notify('Пароль изменён. Другие сеансы завершены.')}catch(e){setError(e.message)}finally{setBusy(false)}}return <form className="card padded narrow" onSubmit={save}><KeyRound size={27}/><h2>Изменить пароль</h2><Field label="Текущий пароль" type="password" autoComplete="current-password" value={current} onChange={e=>setCurrent(e.target.value)} required/><Field label="Новый пароль" hint="Не менее 12 символов. Используйте уникальный пароль." type="password" autoComplete="new-password" minLength={12} value={password} onChange={e=>setPassword(e.target.value)} required/><Field label="Повторите новый пароль" type="password" autoComplete="new-password" value={repeat} onChange={e=>setRepeat(e.target.value)} required/><ErrorBox>{error}</ErrorBox><button className="button" disabled={busy}>Изменить пароль</button></form>}
function UserSettings({notify,current}){const state=useLoad('/admin/users'),[editing,setEditing]=React.useState(null);return <><div className="toolbar"><p className="muted">Администратор — все права; редактор — контент; менеджер — обращения.</p><button className="button" onClick={()=>setEditing({})}><Plus size={17}/>Добавить пользователя</button></div><ErrorBox>{state.error}</ErrorBox>{state.loading?<Loading/>:<div className="card table-wrap"><table><thead><tr><th>Пользователь</th><th>Роль</th><th>Доступ</th><th>Последний вход</th><th/></tr></thead><tbody>{state.data?.items.map(u=><tr key={u.id}><td><b>{u.name}</b><small className="block muted">{u.email}</small></td><td>{roles[u.role]}</td><td><span className={'pill '+(!u.active?'gray':'')}>{u.active?'Активен':'Отключён'}</span></td><td className="muted">{date(u.last_login)}</td><td><button className="button secondary small" onClick={()=>setEditing(u)}>Изменить</button></td></tr>)}</tbody></table></div>}{editing&&<UserModal user={editing} current={current} onClose={()=>setEditing(null)} onSaved={()=>state.reload()} notify={notify}/>}</>}
function UserModal({user,current,onClose,onSaved,notify}){const [data,setData]=React.useState({name:'',email:'',role:'editor',active:true,password:'',...user}),[busy,setBusy]=React.useState(false),[error,setError]=React.useState('');const change=(key,value)=>setData(d=>({...d,[key]:value}));async function save(e){e.preventDefault();setBusy(true);setError('');try{await api('/admin/users'+(user.id?'/'+user.id:''),{method:user.id?'PUT':'POST',body:data});notify(user.id?'Пользователь обновлён':'Пользователь создан');onSaved();onClose()}catch(e){setError(e.message)}finally{setBusy(false)}}return <Modal title={user.id?'Изменить пользователя':'Новый пользователь'} onClose={onClose}><form onSubmit={save}><Field label="Имя" value={data.name} onChange={e=>change('name',e.target.value)} required/><Field label="Email для входа" type="email" value={data.email} disabled={!!user.id} onChange={e=>change('email',e.target.value)} required/><Field label="Роль"><select value={data.role} disabled={user.id===current.id} onChange={e=>change('role',e.target.value)}>{Object.entries(roles).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></Field><Field label={user.id?'Новый пароль (если нужно изменить)':'Начальный пароль'} hint="Не менее 12 символов. Передайте пользователю отдельно." type="password" autoComplete="new-password" minLength={12} value={data.password} onChange={e=>change('password',e.target.value)} required={!user.id}/>{user.id&&<label className="checkbox"><input type="checkbox" checked={!!data.active} disabled={user.id===current.id} onChange={e=>change('active',e.target.checked)}/>Доступ активен</label>}<ErrorBox>{error}</ErrorBox><div className="actions end"><button className="button secondary" type="button" onClick={onClose}>Отмена</button><button className="button" disabled={busy}>Сохранить</button></div></form></Modal>}
function Audit(){const state=useLoad('/admin/audit');const actions={login:'Вход',save:'Черновик',publish:'Публикация',create:'Создание',archive:'Архив',unarchive:'Восстановление',upload:'Загрузка','media-edit':'Изображение',settings:'Настройки','user-create':'Пользователь','user-edit':'Доступ','lead-status':'Обращение',password:'Пароль'};return <div className="card padded"><h2>Последние действия</h2><ErrorBox>{state.error}</ErrorBox>{state.loading?<Loading/>:state.data?.items.length?<div className="audit-list">{state.data.items.map(a=><div className="history-row" key={a.id}><History size={18}/><div><b>{actions[a.action]||a.action} · {a.label}</b><small>{a.actor}</small></div><span className="muted">{date(a.created_at)}</span></div>)}</div>:<Empty title="Журнал пока пуст"/>}</div>}
