import React from 'react';
import {Upload,ImagePlus,Check,ArrowLeft,RefreshCw,ExternalLink,Images} from 'lucide-react';
import {api,useLoad,Loading,ErrorBox,Empty,Heading,Field,SearchBox,Modal,Pagination} from './core';
export function MediaGrid({onPick,notify,compact=false}){
 const [search,setSearch]=React.useState(''),[query,setQuery]=React.useState(''),[page,setPage]=React.useState(1),[uploading,setUploading]=React.useState(false),[error,setError]=React.useState(''),[detail,setDetail]=React.useState(null);
 React.useEffect(()=>{const t=setTimeout(()=>{setQuery(search);setPage(1)},250);return()=>clearTimeout(t)},[search]);
 const state=useLoad('/admin/media?q='+encodeURIComponent(query)+'&page='+page);
 async function upload(files){setUploading(true);setError('');let last;try{for(const file of files){const form=new FormData();form.append('file',file);last=await api('/admin/media',{method:'POST',body:form})}state.reload();notify?.('Изображения загружены');}catch(e){setError(e.message)}finally{setUploading(false)}}
 return <><div className="toolbar"><SearchBox value={search} onChange={setSearch} placeholder="Название или описание изображения"/><label className={'button '+(uploading?'disabled':'')}><Upload size={17}/>{uploading?'Загрузка…':'Загрузить'}<input type="file" hidden accept="image/jpeg,image/png,image/webp,image/gif" multiple disabled={uploading} onChange={e=>{upload([...e.target.files]);e.target.value=''}}/></label></div><ErrorBox>{error||state.error}</ErrorBox>{state.loading?<Loading/>:state.data?.items.length?<div className={'media-grid '+(compact?'compact':'')}>{state.data.items.map(m=><button key={m.id} className="media-item" onClick={()=>onPick?onPick(m):setDetail(m)} title={m.name}><div className="media-image"><img loading="lazy" src={m.url} alt={m.alt||m.name}/>{m.source==='upload'&&<span className="media-new">Загружено</span>}</div><div className="media-caption"><b>{m.name}</b><small>{m.type.toUpperCase()} · {m.size>1048576?(m.size/1048576).toFixed(1)+' МБ':Math.round(m.size/1024)+' КБ'}</small></div></button>)}</div>:<Empty title="Изображения не найдены" text="Попробуйте другой запрос или загрузите новое изображение." icon={Images}/>}<Pagination page={page} total={state.data?.total||0} onChange={setPage}/>{detail&&<MediaDetail media={detail} notify={notify} onClose={()=>setDetail(null)} onSaved={()=>state.reload()}/>}</>
}
export function MediaPicker({onPick,onClose,notify}){return <Modal title="Выберите изображение" onClose={onClose} wide><MediaGrid onPick={onPick} notify={notify} compact/></Modal>}
export function MediaDetail({media,onClose,onSaved,notify}){
 const [name,setName]=React.useState(media.name),[alt,setAlt]=React.useState(media.alt),[busy,setBusy]=React.useState(false),[error,setError]=React.useState(''),[picker,setPicker]=React.useState(false),[target,setTarget]=React.useState(null),[family,setFamily]=React.useState(true),[confirm,setConfirm]=React.useState(null);
 const pages=JSON.parse(media.pages||'[]');
 async function save(){setBusy(true);setError('');try{await api('/admin/media/'+media.id,{method:'PUT',body:{name,alt}});notify('Подпись изображения сохранена');onSaved();}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function prepare(m){setPicker(false);setTarget(m);setError('');try{setConfirm(await api('/admin/content/globals'))}catch(e){setError(e.message)}}
 async function replace(publish){setBusy(true);setError('');try{const r=await api('/admin/media/'+media.id+'/replace',{method:'POST',body:{targetId:target.id,family,publish,version:confirm.version}});notify((publish?'Изображение заменено на сайте':'Замена сохранена в черновике')+' · '+r.replaced+' вариант(ов)');onSaved();onClose()}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <Modal title="Изображение" onClose={onClose} wide><div className="media-detail"><div className="media-detail-image"><img src={target?.url||media.url} alt={alt}/><a href={media.url} className="button secondary small" target="_blank" rel="noreferrer">Открыть оригинал <ExternalLink size={15}/></a></div><div><Field label="Название файла" value={name} onChange={e=>setName(e.target.value)}/><Field label="Описание изображения (alt)" hint="Кратко опишите, что изображено. Это помогает поиску и людям с нарушениями зрения."><textarea rows={3} value={alt} onChange={e=>setAlt(e.target.value)}/></Field><button className="button" disabled={busy} onClick={save}>Сохранить подпись</button><hr/><h3>Заменить на сайте</h3><p className="muted">Замена применяется ко всем местам, где используется это изображение. Исходный файл останется в медиатеке.</p><button className="button secondary" onClick={()=>setPicker(true)}><RefreshCw size={17}/>Выбрать замену</button>{target&&<div className="notice"><b>Новое изображение: {target.name}</b><label className="checkbox"><input type="checkbox" checked={family} onChange={e=>setFamily(e.target.checked)}/> Заменить также уменьшенные версии</label><div className="actions"><button className="button secondary small" disabled={busy||!confirm} onClick={()=>replace(false)}>В черновик</button><button className="button small" disabled={busy||!confirm} onClick={()=>replace(true)}>Опубликовать замену</button></div></div>}<ErrorBox>{error}</ErrorBox>{pages.length>0&&<details><summary>Используется на {pages.length} страницах</summary><div className="link-list">{pages.map(id=><a key={id} href={'#edit/'+id} onClick={onClose}>{id==='home'?'Главная':id.replaceAll('__',' / ')}</a>)}</div></details>}</div></div>{picker&&<MediaPicker notify={notify} onClose={()=>setPicker(false)} onPick={prepare}/>}</Modal>
}
export function MediaPage({notify}){return <><Heading title="Медиатека" description="Все изображения сайта. Загружайте, описывайте и заменяйте."/><MediaGrid notify={notify}/></>}
