import React from 'react';
import {useLoad,Loading,Modal} from './core';
import {MediaPicker} from './media';
export default function PageImages({ids,notify,mediaMap,onReplace}){
 const state=useLoad('/admin/media?ids='+(ids||[]).join(',')),[selected,setSelected]=React.useState(null),[target,setTarget]=React.useState(null),[family,setFamily]=React.useState(true);
 const stem=url=>url.replace(/(?:-\d+x\d+|-scaled)?\.[^.]+$/,'');
 const all=state.data?.items||[];const groups=new Map();for(const m of all){const key=stem(m.url),old=groups.get(key);if(!old||m.size>old.size)groups.set(key,m)}
 function apply(){const map={};for(const m of all)if(m.id===selected.id||family&&stem(m.url)===stem(selected.url))map[m.id]=target.id;onReplace(map);setSelected(null);setTarget(null);notify('Изображение выбрано. Сохраните или опубликуйте страницу.');}
 return <><p className="hint">Изображения этой страницы. Нажмите на изображение, чтобы заменить его только здесь.</p>{state.loading?<Loading/>:<div className="media-grid compact">{[...groups.values()].map(m=><button key={m.id} className="media-item" onClick={()=>setSelected(m)} title={m.name}><div className="media-image"><img loading="lazy" src={m.url} alt={m.alt||m.name}/>{mediaMap?.[m.id]&&<span className="media-new">Есть замена</span>}</div><div className="media-caption"><b>{m.name}</b></div></button>)}</div>}{selected&&!target&&<MediaPicker notify={notify} onClose={()=>setSelected(null)} onPick={setTarget}/>} {target&&<Modal title="Замена на этой странице" onClose={()=>{setSelected(null);setTarget(null)}}><div className="og-image"><img src={target.url} alt={target.name}/><b>{target.name}</b></div><label className="checkbox"><input type="checkbox" checked={family} onChange={e=>setFamily(e.target.checked)}/>Заменить также уменьшенные версии</label><p className="hint">Замена сохранится вместе с остальными изменениями страницы.</p><button className="button" onClick={apply}>Применить в редакторе</button></Modal>}</>}
